# vim: set ts=4 sw=4 expandtab:
[config]
additional_profiles = [ "release" ]

[env]
PLATFORM_DYLIB_EXT = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "so", mapping = {"macos" = "dylib", "windows" = "dll" } }
PLATFORM_EXTERNAL_EXT = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "ERROR", mapping = {"macos" = "mxo", "windows" = "mxe64"} }
PLATFORM_INSTALL_DIR = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "ERROR", mapping = {"macos" = "${HOME}/Documents/Max 8/Packages", windows = "${USERPROFILE}/Documents/Max 8/Packages" } }
PACKAGE_INSTALL_DIR = "${PLATFORM_INSTALL_DIR}/median/externals/"
PLATFORM_DYLIB_PREFIX = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "lib", mapping = {"windows" = ""} }
LIB_FILE_NAME = "${PLATFORM_DYLIB_PREFIX}${CARGO_MAKE_CRATE_FS_NAME}.${PLATFORM_DYLIB_EXT}"
LIB_TILDE_FILE_NAME = "${PLATFORM_DYLIB_PREFIX}${CARGO_MAKE_CRATE_FS_NAME}_tilde.${PLATFORM_DYLIB_EXT}"
PACKAGED_LIB_FILE_NAME = "${CARGO_MAKE_CRATE_FS_NAME}"

[env.development]
BUILD_ARGS = "build"
PROFILE_TARGET_DIR = "target/debug"

[env.release]
BUILD_ARGS = "build|--release"
PROFILE_TARGET_DIR = "target/release"

[tasks.build]
args = ["@@split(BUILD_ARGS,|)"]

[tasks.name-env]
dependencies = ["build"]
env = { "PROFILE_PACKAGE_PATH" = "${PROFILE_TARGET_DIR}/${CARGO_MAKE_CRATE_FS_NAME}.${PLATFORM_EXTERNAL_EXT}" }
run_task = "add_tilde"

#see if we should add a tilde
[tasks.add_tilde]
private = true
condition = { files_exist = ["${PROFILE_TARGET_DIR}/${LIB_TILDE_FILE_NAME}"] }
env = { "PROFILE_PACKAGE_PATH" = "${PROFILE_TARGET_DIR}/${CARGO_MAKE_CRATE_FS_NAME}~.${PLATFORM_EXTERNAL_EXT}", "LIB_FILE_NAME" = "${LIB_TILDE_FILE_NAME}", "PACKAGED_LIB_FILE_NAME" = "${PACKAGED_LIB_FILE_NAME}~" }


[tasks.echo]
dependencies = ["name-env"]
script_runner = "@shell"
script = [
'''
echo PLATFORM_DYLIB_EXT: ${PLATFORM_DYLIB_EXT}
echo PLATFORM_EXTERNAL_EXT: ${PLATFORM_EXTERNAL_EXT}
echo PLATFORM_INSTALL_DIR: ${PLATFORM_INSTALL_DIR}
echo PROFILE_PACKAGE_PATH: ${PROFILE_PACKAGE_PATH}
echo PACKAGE_INSTALL_DIR: ${PACKAGE_INSTALL_DIR}
echo CARGO_MAKE_PROJECT_NAME: ${CARGO_MAKE_PROJECT_NAME}
echo LIB_FILE_NAME: ${LIB_FILE_NAME}
echo LIB_TILDE_FILE_NAME: ${LIB_TILDE_FILE_NAME}
'''
]

[tasks.package.windows]
clear = true
dependencies = ["build", "name-env"]
script_runner = "@shell"
script = [
    '''
    cp "${PROFILE_TARGET_DIR}/${LIB_FILE_NAME}" "${PROFILE_PACKAGE_PATH}"
    '''
]

[tasks.package.mac]
clear = true
dependencies = ["build", "name-env"]
script_runner = "@shell"
script = [
    '''
    mkdir -p ${PROFILE_PACKAGE_PATH}/Contents/MacOS/
    cp "${PROFILE_TARGET_DIR}/${LIB_FILE_NAME}" "${PROFILE_PACKAGE_PATH}/Contents/MacOS/${PACKAGED_LIB_FILE_NAME}"
    cp "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/PkgInfo" "${PROFILE_PACKAGE_PATH}/Contents/"
    '''
]

[tasks.install.windows]
clear = true
dependencies = ["package"]
script_runner = "powershell"
script_extension = "ps1"
script = [
    '''
    if((Test-Path $env:PACKAGE_INSTALL_DIR) -eq 0)
    {
        New-Item $env:PACKAGE_INSTALL_DIR -ItemType Directory
    }
    Copy-Item $env:PROFILE_PACKAGE_PATH -Destination $env:PACKAGE_INSTALL_DIR
    '''
]

[tasks.install.mac]
clear = true
dependencies = ["package"]
script_runner = "@shell"
script = [
    '''
    mkdir -p "${PACKAGE_INSTALL_DIR}"
    cp -r "${PROFILE_PACKAGE_PATH}" "${PACKAGE_INSTALL_DIR}"
    '''
]

