[package]
name = "multi"
version = "0.1.0"
authors = ["Alex Norman <xnor@cycling74.com>"]
edition = "2018"

[lib]
name = "multi"
crate-type = ["cdylib"]

[dependencies]
median = { path = "../../" }

[profile.release]
lto = true
panic = "abort"
