[package]
name = "hello_dsp"
version = "0.1.0"
authors = ["Alex Norman <xnor@cycling74.com>"]
edition = "2018"

[lib]
name = "hello_dsp"
crate-type = ["cdylib"]

[dependencies]
max-sys = { path = "../../../max-sys/" }
median = { path = "../../" }

[profile.release]
lto = true
panic = "abort"
