[package]
name = "{{project-name}}"
version = "0.1.0"
authors = [ "{{ authors }}" ]
edition = "2018"

[lib]
name = "{{crate_name}}"
crate-type = ["cdylib"]

[dependencies]
median = { git = "https://github.com/Cycling74/median" }

[profile.release]
lto = true
panic = "abort"
